eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defautlZone: http://loclahost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: asus7532159
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
